= Changelog

:sectnums!:

== link:++https://github.com/saltstack-formulas/stunnel-formula/compare/v0.2.2...v0.2.3++[0.2.3^] (2020-12-16)

=== Bug Fixes

* *release.config.js:* use full commit hash in commit link [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/d37e769b09803e321dd07e74cd450c0cb1761825[d37e769^])

=== Continuous Integration

* *gemfile:* restrict `train` gem version until upstream fix [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/8bec93c5a190f00fcb57be89d486d4252a2986d8[8bec93c^])
* *gemfile.lock:* add to repo with updated `Gemfile` [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/a17dc3162e8cf810b3e63ccd0742497e12c5d577[a17dc31^])
* *gitlab-ci:* use GitLab CI as Travis CI replacement
(https://github.com/saltstack-formulas/stunnel-formula/commit/7ad0d6362c7d61b85e1a54e5b05b7760051f0ddb[7ad0d63^])
* *kitchen:* avoid using bootstrap for `master` instances [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/4b249dc3e409c829eabc23116105328019e75cbb[4b249dc^])
* *kitchen:* use `debian-10-master-py3` instead of `develop` [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/3b9588a16586cd498111142e40021124ccf88ac5[3b9588a^])
* *kitchen:* use `develop` image until `master` is ready (`amazonlinux`)
 [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/31b5081863dd5dae492b25ec0ae0640ab66948e8[31b5081^])
* *kitchen:* use `saltimages` Docker Hub where available [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/0252b54b2c6cae66872be4ea9af9b97ddca54685[0252b54^])
* *kitchen+travis:* remove `master-py2-arch-base-latest` [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/564e12e1e04b7aeb580435e86aa495050951fae7[564e12e^])
* *kitchen+travis:* upgrade matrix after `2019.2.2` release [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/d9eaec662afeaaf2ee83c4c9455971c001b362ec[d9eaec6^])
* *pre-commit:* add to formula [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/9ce264c34c8cb22b2ee58e1c7339b55b29ddcc3a[9ce264c^])
* *pre-commit:* enable/disable `rstcheck` as relevant [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/1c0c322cef909a76a739f36a38d141f887202660[1c0c322^])
* *pre-commit:* finalise `rstcheck` configuration [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/8bc48071a1b69fbfbd95aa1f0e92815bdb6d2a52[8bc4807^])
* *travis:* add notifications => zulip [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/e6125ff1a08aae66f5c817a57d3667fe256f9e03[e6125ff^])
* *travis:* apply changes from build config validation [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/d92fc95cf1b41008259680e5bca930746e61f2ba[d92fc95^])
* *travis:* opt-in to `dpl v2` to complete build config validation [skip
ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/62865ca241e9aec743434a56e84b031a50ab1334[62865ca^])
* *travis:* quote pathspecs used with `git ls-files` [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/7af7f1f551fe8b7fb87e5af4b17d7edb0ba95f6e[7af7f1f^])
* *travis:* run `shellcheck` during lint job [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/fa08c3de83f3aa085fed16334d21b246d72dd4d5[fa08c3d^])
* *travis:* update `salt-lint` config for `v0.0.10` [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/a5211ff103dcb829c3d842fbc1e285a4398d30ca[a5211ff^])
* *travis:* use `major.minor` for `semantic-release` version [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/38e9777e2ffe80350948cd08d53c988764b93985[38e9777^])
* *travis:* use build config validation (beta) [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/a37e169478513c3d21a251193aa6c27f4f3e61c0[a37e169^])
* *workflows/commitlint:* add to repo [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/e8c4509a6d41e0c26da9580c4313efbf594a4b77[e8c4509^])

=== Documentation

* *contributing:* remove to use org-level file instead [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/7ae0f304a5c5cbb4dd29bc01ef7c72dda065d4a5[7ae0f30^])
* *readme:* update link to `CONTRIBUTING` [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/410ce1b3aa6a5c489ed6e8dcd39ed97bb48aff7f[410ce1b^])

=== Performance Improvements

* *travis:* improve `salt-lint` invocation [skip ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/c6dc65c33fb90ab498cb94a52ef2292c9e1c5044[c6dc65c^])

== link:++https://github.com/saltstack-formulas/stunnel-formula/compare/v0.2.1...v0.2.2++[0.2.2^] (2019-10-12)

=== Bug Fixes

* *rubocop:* add fixes using `rubocop --safe-auto-correct`
(https://github.com/saltstack-formulas/stunnel-formula/commit/3738a21[3738a21^])

=== Continuous Integration

* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/stunnel-formula/commit/687e84f[687e84f^])
* *travis:* merge `rubocop` linter into main `lint` job
(https://github.com/saltstack-formulas/stunnel-formula/commit/823496b[823496b^])

== link:++https://github.com/saltstack-formulas/stunnel-formula/compare/v0.2.0...v0.2.1++[0.2.1^] (2019-10-10)

=== Bug Fixes

* *macro.jinja:* fix `salt-lint` errors
(https://github.com/saltstack-formulas/stunnel-formula/commit/09646f9[09646f9^])
* *pillar_certs.sls:* fix `salt-lint` errors
(https://github.com/saltstack-formulas/stunnel-formula/commit/79100c1[79100c1^])

=== Continuous Integration

* *kitchen:* install required packages to bootstrapped `opensuse` [skip
ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/219bf04[219bf04^])
* *kitchen:* use bootstrapped `opensuse` images until `2019.2.2` [skip
ci]
(https://github.com/saltstack-formulas/stunnel-formula/commit/9c9a58d[9c9a58d^])
* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/stunnel-formula/commit/94f95e2[94f95e2^])

== link:++https://github.com/saltstack-formulas/stunnel-formula/compare/v0.1.1...v0.2.0++[0.2.0^] (2019-09-25)

=== Bug Fixes

* *pillar.example:* ensure comments would pass `yamllint` as well
(https://github.com/saltstack-formulas/stunnel-formula/commit/e2f5a95[e2f5a95^])

=== Continuous Integration

* *kitchen:* add binstub for Kitchen command
(https://github.com/saltstack-formulas/stunnel-formula/commit/d373390[d373390^])
* *kitchen:* extract test pillars in file
(https://github.com/saltstack-formulas/stunnel-formula/commit/924fd71[924fd71^])
* *kitchen:* fix stunnel don't start because certs are missing
(https://github.com/saltstack-formulas/stunnel-formula/commit/ce6971f[ce6971f^])
* *kitchen:* rename Kitchen config file
(https://github.com/saltstack-formulas/stunnel-formula/commit/e83fa64[e83fa64^])
* *kitchen:* update gems
(https://github.com/saltstack-formulas/stunnel-formula/commit/1110a9d[1110a9d^])
* *kitchen:* update platforms list
(https://github.com/saltstack-formulas/stunnel-formula/commit/1264438[1264438^])
* *travis:* run tests on Debian/Ubuntu first
(https://github.com/saltstack-formulas/stunnel-formula/commit/403c025[403c025^])

=== Features

* *semantic-release:* add semantic-release
(https://github.com/saltstack-formulas/stunnel-formula/commit/261f484[261f484^])
* *semantic-release:* implement for this formula
(https://github.com/saltstack-formulas/stunnel-formula/commit/9cd995a[9cd995a^])

=== Tests

* *inspec:* add Inspec tests
(https://github.com/saltstack-formulas/stunnel-formula/commit/5650446[5650446^])
